[build]
  cmd = "/Users/bensuskins/go/bin/templ generate && npx tailwindcss -i ./static/css/input.css -o ./static/css/styles.css --minify && go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "node_modules", "data", ".git"]
  exclude_regex = ["_test\\.go$", "_templ\\.go$"]
  include_ext = ["go", "templ", "css", "js"]
  kill_delay = "0s"

[log]
  time = false

[misc]
  clean_on_exit = true
